language: java
dist: trusty

jdk:
  - oraclejdk8
  
cache:
  directories:
  - "$HOME/.gradle/caches"  
 
services:
  - redis-server
  - rabbitmq
  
addons:
  apt:
    sources:
      - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
    packages:
      - mosquitto  
  
before_script:
  # install NATS server
  - wget https://github.com/nats-io/gnatsd/releases/download/v1.1.0/gnatsd-v1.1.0-linux-amd64.zip -qO gnatsd.zip
  - unzip gnatsd.zip
  - ./gnatsd-v1.1.0-linux-amd64/gnatsd &
  - wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
  - sudo apt-key add mosquitto-repo.gpg.key
  - cd /etc/apt/sources.list.d/
  - sudo wget http://repo.mosquitto.org/debian/mosquitto-jessie.list
  - sudo apt-get update  
  #- sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa -y
  #- sudo apt-get update -y
  #- sudo apt-get install mosquitto -y
   
install: gradle wrapper --gradle-version 4.2
  
before_install:
  - chmod +x gradlew
  
# script: ./gradlew -i check
script: ./gradlew check

after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)
